name: 'setup'
description: Prepare the environment

inputs:
  npm-token:
    description: 'npm token'
    required: false

runs:
  using: composite
  steps:
    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 9
        run_install: false

    - name: Setup pnpm config
      shell: bash
      run: pnpm config set store-dir .pnpm-store

    - name: Cache pnpm
      uses: actions/cache@v4
      with:
        path: |
          common/temp/pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Creating .npmrc
      if: inputs.npm-token != ''
      shell: bash
      run: |
        cat << EOF > "$HOME/.npmrc"
          //registry.npmjs.org/:_authToken=$NPM_TOKEN
        EOF
      env:
        NPM_TOKEN: ${{ inputs.npm-token }}
