name: github-pages-cicd

inputs:
  server-endpoint:
    description: 'server endpoint'
    required: true
  wallet-connect-project-id:
    description: 'wallet connect project id'
    required: true
  api-token-github:
    description: 'api token github'
    required: true

runs:
  using: composite
  steps:
    - name: Creating .env
      shell: bash
      run: |
        cat << EOF > "./apps/canonical-bridge-ui/.env"
          NEXT_PUBLIC_APP_NAME=$APP_NAME
          NEXT_PUBLIC_BASE_PATH=$BASE_PATH
          NEXT_PUBLIC_ASSET_PREFIX=$ASSET_PREFIX
          NEXT_PUBLIC_SERVER_ENDPOINT=$SERVER_ENDPOINT
          NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=$WALLET_CONNECT_PROJECT_ID
        EOF
      env:
        APP_NAME: canonical-bridge
        BASE_PATH: /canonical-bridge
        ASSET_PREFIX: /canonical-bridge
        SERVER_ENDPOINT: ${{ inputs.server-endpoint }}
        WALLET_CONNECT_PROJECT_ID: ${{ inputs.wallet-connect-project-id }}

    - name: Install & build
      shell: bash
      run: |
        node common/scripts/install-run-rush.js install -t @bnb-chain/canonical-bridge-ui
        node common/scripts/install-run-rush.js build -t @bnb-chain/canonical-bridge-ui

    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ inputs.api-token-github }}
      with:
        source-directory: './apps/canonical-bridge-ui/dist'
        destination-github-username: 'wenty22'
        destination-repository-name: 'canonical-bridge'
        user-email: github-actions[bot]@users.noreply.github.com
        target-branch: main

    # - name: Deploy docs
    #   uses: JamesIves/github-pages-deploy-action@v4
    #   with:
    #     folder: ./apps/canonical-bridge-ui/dist
    #     branch: 'gh-pages'
    #     clean: true
    #     force: true
