name: alpha

inputs:
  app-name:
    description: 'app name'
    required: true
  npm-token:
    description: 'npm token'
    required: true
  github-token:
    description: 'github token'
    required: true
  branch:
    description: 'branch'
    required: true

runs:
  using: composite
  steps:
    - name: Install & build
      shell: bash
      run: |
        node .release/scripts/install.js

        node common/scripts/install-run-rush.js install -t @bnb-chain/$APP_NAME
        node common/scripts/install-run-rush.js build -t @bnb-chain/$APP_NAME
      env:
        APP_NAME: ${{inputs.app-name}}

    - name: Create and publish versions
      uses: changesets/action@v1
      with:
        version: pnpm ci:alpha-version
        publish: pnpm ci:publish
        commit: 'chore: Update versions'
        title: 'chore: Update versions'
        cwd: '.release'
        branch: ${{ inputs.branch }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
