name: github-pages-cicd

on:
  issue_comment:
    types: [created]

jobs:
  build:
    if: github.repository == 'bnb-chain/canonical-bridge' && contains(github.event.comment.body, '/qa-deploy')
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: 'CD canonical-bridge-ui'
        run: cd ./apps/canonical-bridge-ui

      - name: Creating .env
        shell: bash
        run: |
          cat << EOF > ".env"
            NEXT_PUBLIC_APP_NAME=$APP_NAME
            NEXT_PUBLIC_BASE_PATH=$BASE_PATH
            NEXT_PUBLIC_ASSET_PREFIX=$ASSET_PREFIX
            NEXT_PUBLIC_SERVER_ENDPOINT=$SERVER_ENDPOINT
            NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=$WALLET_CONNECT_PROJECT_ID
          EOF
          ls -a
          cat .env
        env:
          APP_NAME: canonical-bridge-ui
          BASE_PATH: /canonical-bridge-ui
          ASSET_PREFIX: /canonical-bridge-ui
          SERVER_ENDPOINT: ${{ vars.SERVER_ENDPOINT }}
          WALLET_CONNECT_PROJECT_ID: ${{ vars.WALLET_CONNECT_PROJECT_ID }}

      - name: Install & build
        shell: bash
        run: |
          node common/scripts/install-run-rush.js install -t canonical-bridge-ui
          node common/scripts/install-run-rush.js build -t canonical-bridge-ui

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
          branch: 'gh-pcages'
          clean: true
          force: true
