name: qa-cicd-by-comment

on:
  issue_comment:
    types: [created]

jobs:
  cicd-ap-pr:
    uses: bnb-chain/github-workflow/.github/workflows/fe-qa-cicd-ap.yml@main
    secrets: inherit
    with:
      app_name: multichain-bridge-ui
