name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  release:
    if: github.repository == 'bnb-chain/canonical-bridge'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Creating .npmrc
        shell: bash
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install & build
        shell: bash
        run: |
          node .release/scripts/install.js

          node common/scripts/install-run-rush.js install -t @bnb-chain/canonical-bridge-sdk
          node common/scripts/install-run-rush.js build -t @bnb-chain/canonical-bridge-sdk

          node common/scripts/install-run-rush.js install -t @bnb-chain/canonical-bridge-widget
          node common/scripts/install-run-rush.js build -t @bnb-chain/canonical-bridge-widget

      - name: Create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm ci:stable-version
          publish: pnpm ci:publish
          commit: 'chore: Update versions'
          title: 'chore: Update versions'
          cwd: '.release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
