name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - wenty/test

jobs:
  release:
    name: release
    if: github.repository == 'bnb-chain/canonical-bridge'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Check changeset
        shell: bash
        id: 'changeset'
        run: |
          result=$(node common/scripts/install-run-rush.js ci:verify 2>&1) || true

          if [[ $result == *"Found change file"* ]]; then
            echo shouldPublish=true >> $GITHUB_OUTPUT
          fi

      - name: Apply changeset
        if: steps.changeset.outputs.shouldPublish
        shell: bash
        run: |
          node common/scripts/install-run-rush.js build
          node common/scripts/install-run-rush.js publish --apply
          node common/scripts/install-run-rush.js update

      - name: Create PR
        if: steps.changeset.outputs.shouldPublish
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore: Update versions'
          title: 'chore: Update versions'
          delete-branch: true
          branch: 'release'

      - name: Release
        if: github.event.pull_request.merged == true && github.head_ref == 'release'
        id: 'release'
        run: |
          node common/scripts/install-run-rush.js build
          cat << EOF > "./common/config/rush/.npmrc-publish"
            //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          EOF
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          node common/scripts/install-run-rush.js publish --include-all --publish --target-branch ${{github.base_ref}}
          echo shouldGenerateReleaseNotes=true >> $GITHUB_OUTPUT

      - uses: release-drafter/release-drafter@v6
        if: steps.release.outputs.shouldGenerateReleaseNotes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
