name: Release server

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - apps/canonical-bridge-server/**

jobs:
  pre-check:
    runs-on: ubuntu-latest
    if: github.repository == 'bnb-chain/canonical-bridge'
    outputs:
      codeowners: ${{ steps.codeowners.outputs.content }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read codeowners
        id: codeowners
        uses: juliangruber/read-file-action@v1
        with:
          path: .github/CODEOWNERS

  cicd:
    needs: [pre-check]
    if: contains(needs.pre-check.outputs.codeowners, github.event.pull_request.merged_by.login)
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Create server docker
        uses: ./.github/actions/server
